[package]
name = "variable-bindings"
version = "0.1.0"
authors = ["Anderson Dorow <Anderson.Dorow@zooplus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
